<?php
// Define the API token securely
$authToken = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJMX1gzeDFTbV94OXh3TXpXZUNkT2YzbXZJWEk4WmVBWlY4bTY5TDhLNDNnIn0.eyJleHAiOjE3MzY4MDM1NDIsImlhdCI6MTczNjc2NzU0MiwianRpIjoiYmNkY2ZiZTgtNDQwYS00NzhmLWIzMzQtOTk2NjMzY2Q4OTY3IiwiaXNzIjoiaHR0cDovLzE5Mi4xNjguMjQ1LjIxOjgwMDIvYXV0aC9yZWFsbXMvYmFuYmVpcyIsImF1ZCI6WyJyZWFsbS1tYW5hZ2VtZW50IiwiYWNjb3VudCJdLCJzdWIiOiJiMWNhNjBiMy1lYTU4LTQxYjAtYmJmOC04OWU4YzhhNzMyYzYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJJRUlNUyIsInNlc3Npb25fc3RhdGUiOiJmNjU4ZjBmNC01YjYwLTQ2OTItOTA0Ny1jNjUyNjU1MWJiNmEiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImRlZmF1bHQtcm9sZXMtYmFuYmVpcyIsIkluc3RpdHV0ZUFkbWluIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsicmVhbG0tbWFuYWdlbWVudCI6eyJyb2xlcyI6WyJtYW5hZ2UtcmVhbG0iLCJ2aWV3LXVzZXJzIiwicXVlcnktZ3JvdXBzIiwicXVlcnktdXNlcnMiXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoidXNlcm5hbWUgZW1haWwgcHJvZmlsZSIsInNpZCI6ImY2NThmMGY0LTViNjAtNDY5Mi05MDQ3LWM2NTI2NTUxYmI2YSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwidXNlcl9pZCI6ImIxY2E2MGIzLWVhNTgtNDFiMC1iYmY4LTg5ZThjOGE3MzJjNiIsIkV4YW1pbmVyIjpbIkV4YW1pbmVyZGVmYXVsdC1yb2xlcy1iYW5iZWlzIiwiRXhhbWluZXJJbnN0aXR1dGVBZG1pbiJdLCJ1c2VyX25hbWUiOiIxMDEwNDUiLCJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLWJhbmJlaXMiLCJJbnN0aXR1dGVBZG1pbiJdLCJlaWluX25vIjoiMTAxMDQ1IiwiaW5zdGl0dXRlX2lkIjoiMzI4MTQiLCJnaXZlbl9uYW1lIjoiIiwiZmFtaWx5X25hbWUiOiIiLCJlbWFpbCI6InNjaG9vbDEwMTA0NUBnbWFpbC5jb20iLCJpbnN0aXR1dGVfdHlwZV9pZCI6IjExIn0.X0og6CMBs1H5NatOz96PCiXhTjW63u5BHz_VzjMhBKEuQMOIDteyDYXy6KuyyvI0MOnFra1Im-n4JXqVAs7sY8Q7mSAuqZbUd7Jg_ihmVTIqIyjVwDWIlNuPaFBiFIPLo7-zrcZEhUtoyn7Vwr4t6M674aWqFZ9IT6NRXt_yT_whjhynk2vShb2n1bowEbYeyDFLR-9xkUtm8qJKELDa35XyzTKAm-1m-ZRAr6tRkGAtSG7BmVTApNkio_xKHHzi8FK8-GFWlYqgkHLHGGGDtEbMjgmXXC9ZWDudVgAMZ1MZnTJJvyRz2tJXicAAq3I425DLSZHZKbXtqSjTehieiQ"; // Replace with your actual API token

// Optionally, ensure token validity by checking against a known expiry
$tokenExpiry = strtotime("2025-12-31 23:59:59"); // Replace with the actual token expiry date and time

if (time() > $tokenExpiry) {
    die(json_encode([
        "status" => "error",
        "message" => "API token has expired. Please update the token."
    ], JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE));
}
?>
